StoreFrontMCV/Models/ErrorViewModel.cs
using System;

namespace StoreFrontMCV.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StoreFrontMCV/Models/Product.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace StoreFrontMCV.Models
{
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double? Price { get; set; }
        public int? Quantity { get; set; }
        public string Description { get; set; }
    }
}

StoreFrontMCV/Models/ProductsDbContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace StoreFrontMCV.Models
{
    public partial class ProductsDbContext : DbContext
    {
        public ProductsDbContext()
        {
        }

        public ProductsDbContext(DbContextOptions<ProductsDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Product> Products { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Server=.\\SQLExpress;Database=ProductsDb;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Product>(entity =>
            {
                entity.Property(e => e.Description).HasMaxLength(300);

                entity.Property(e => e.Name).HasMaxLength(20);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

StoreFrontMCV/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using StoreFrontMCV.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreFrontMCV.Controllers
{
    public class ProductController : Controller
    {
        ProductsDbContext db = new ProductsDbContext();

        public IActionResult ManageProduct()
        {
            return View();
        }
    }
}

StoreFrontMCV/Controllers/StorefrontController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StoreFrontMCV.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StoreFrontMCV.Controllers
{
    public class StorefrontController : Controller
    {
        ProductsDbContext db = new ProductsDbContext();

        public IActionResult MainMenu()
        {
            return View();
        }
      
        public IActionResult Index()
        {
            List<Product> productList = db.Products.ToList();
            return View(productList);
        }

        //this will allow a user to buy a product
        //this is an Update function to the datebase
        public IActionResult Buy(int Id)
        {
            Product p = db.Products.Find(Id);
            return View(p);
        }



        //this will return the result of a purchase
        [HttpPost]
        public IActionResult Result()
        {
            return View();
        }

        public IActionResult ManageProduct()
        {
            return View("ManageProduct", "Inventory");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StoreFrontMCV/Views/Inventory/Delete.cshtml
@model Product
<h5>Delete this product:</h5>

StoreFrontMCV/Views/Inventory/ManageProduct.cshtml
@model IEnumerable<Product>

<h5>Please select an option</h5>
<br />
<a asp-action="AddProduct" asp-controller="ProductController">Add Product</a>
@foreach (Product p in Model)
{
<div style="border: solid black 1px">
    <p>Name: @p.Name</p>
    <p>Price: @p.Price</p>
    <p>Quantity Available: @p.Quantity</p>
    <p>Description: @p.Description</p>
    <a asp-action="Update" asp-controller="ProductController" asp-route-Id="@p.Id">Update</a>
    <a asp-action="Delete" asp-controller="ProductController" asp-route-Id="@p.Id">Delete</a>
</div>
}

StoreFrontMCV/Views/Inventory/Update.cshtml
@model Product
<h5>Update Product</h5>

StoreFrontMCV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StoreFrontMCV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Storefront" asp-action="Index">StoreFrontMCV</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Storefront" asp-action="MainMenu">| MainMenu |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Storefront" asp-action="Index">| Products |</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - StoreFrontMCV - <a asp-area="" asp-controller="Storefront" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

StoreFrontMCV/Views/Storefront/Buy.cshtml
@model Product

<h5>How many you like to purchase:</h5>
<h6>@Model.Name</h6>
<br/>

<form asp-action="Result" method="post">
    <p>Quantity:</p>
    <input type="number" />
    <input type="submit" />
</form>

StoreFrontMCV/Views/Storefront/Index.cshtml
@model IEnumerable<Product>

<h2>Product List</h2>
@foreach(Product p in Model)
{
    <div style="border: solid black 1px">
        <p>Name: @p.Name</p>
        <p>Price: @p.Price</p>
        <p>Quantity Available: @p.Quantity</p>
        <p>Description: @p.Description</p>
        <a asp-action="Buy" asp-controller="Storefront" asp-route-Id="@p.Id">BUY NOW</a>
    </div>
}

StoreFrontMCV/Views/Storefront/MainMenu.cshtml
<a asp-action="Index" asp-controller="Storefront">Product List</a>
<br />
<a asp-action="Inventory" asp-controller="Product">Inventory</a>

StoreFrontMCV/Views/Storefront/Result.cshtml
@model Product
<h3>Your Purchase was Successful!</h3>

<a asp-action="Index" asp-controller="Storefront">Product List</a>
<br />
<a asp-action="MainMenu" asp-controller="Storefront">Main Menu</a>